# Generated by Django 4.0.2 on 2022-05-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='element',
            field=models.IntegerField(null=True),
        ),
    ]
