# Generated by Django 4.0.2 on 2022-05-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoir', '0002_devoir_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='devoir',
            name='sujet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
