# Generated by Django 4.0.2 on 2022-05-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devoir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(null=True, upload_to='documents/')),
                ('etudiant', models.IntegerField()),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitdevoir', to='devoir.devoir')),
            ],
        ),
    ]
