# Generated by Django 4.0.2 on 2022-05-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0004_submit_commentaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='commentaire',
        ),
        migrations.AddField(
            model_name='submit',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
